import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../app/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} flex flex-col min-h-screen`}>
        <header className="top-bar bg-white border-b">
          <div className="con h-20 flex px-[3.725vw] mx-auto">
            <div className="logo-box">
              <Link
                href={"/"}
                className="flex h-full items-center text-xl font-bold"
              >
                📚 SB 포스팅
              </Link>
            </div>
            <nav className="menu-box ml-auto">
              <ul className="flex h-full gap-x-3">
                <li>
                  <Link
                    href={"/post/write"}
                    className="flex h-full items-center h-full"
                  >
                    게시글 작성
                  </Link>
                </li>
                <li>
                  <Link
                    href={"/post/list"}
                    className="flex h-full items-center h-full"
                  >
                    게시글 리스트
                  </Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="main flex-1 flex">{children}</main>
        <footer className="footer h-20 bg-[#afafaf]">
          <div className="inner h-full flex items-center justify-center text-xl font-bold">
            copyright ⓒ 2025 SB 포스팅. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
